### ISSUE TITLE
Thank You!!!

### ISSUE THREAD

**Issue by KerbalNo15** [NothingOSS/android_kernel_devicetree_nothing_sm7325#1]
Releasing device tree files is such a developer friendly move, I can't wait to see what awesome projects the Nothing community makes. I cannot buy a Nothing phone in my country, but if it ever gets released here I think it will be my next device; open source is my #1 priority. Thank you for making the developer community first-class citizens.

**Comment by boehs** [comment]
They are required to by law...

**Comment by xs1vr** [comment]
Except for the terrible back LED design that's appealing only to the incelcore virgins. It's disgustingly cringe+useless.

**Comment by Andboniels** [comment]
> Except for the terrible back LED design that's appealing only to the incelcore virgins. It's disgustingly cringe+useless.

No moderation here? Project is dead
