### ISSUE TITLE
When Android 13 update push

### ISSUE THREAD

**Issue by Divyanshu-Modi** [NothingOSS/android_kernel_devicetree_nothing_sm7325#7]

**Comment by NothingOSS** [comment]
The Android 13 has upedated
https://github.com/NothingOSS/android_kernel_devicetree_nothing_sm7325/tree/sm7325/t

**Comment by Divyanshu-Modi** [comment]
> The Android 13 has upedated https://github.com/NothingOSS/android_kernel_devicetree_nothing_sm7325/tree/sm7325/t

Thx 😊
